#
# https://github.com/Planteome/plant-environment-ontology/tree/master/patterns
#

prefixes:     # User specifies this once per team/project
  CHEBI:
    iriPrefix: http://purl.obolibrary.org/obo/
    autocomplete: ols
  PATO:
    iriPrefix: http://purl.obolibrary.org/obo/
    autocomplete: ols
  PO:
    iriPrefix: http://purl.obolibrary.org/obo/
    autocomplete: ols
  EO:
    iriPrefix: http://purl.obolibrary.org/obo/
    autocomplete: ols
  TO:
    iriPrefix: http://purl.obolibrary.org/obo/
    autocomplete: ols
  GO:
    iriPrefix: http://purl.obolibrary.org/obo/
    autocomplete: solr
  NCBITaxon:
    iriPrefix: http://purl.obolibrary.org/obo/
    autocomplete: ols
  BFO:
    iriPrefix: http://purl.obolibrary.org/obo/
    autocomplete: ols
  ENVO:
    iriPrefix: http://purl.obolibrary.org/obo/
    autocomplete: ols

IRIGeneration:
  prefix: PO
  type: uuid

defaultPatterns:
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/composition.yaml'
    title: 'Composition'
    type: 'yaml'
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/eq.yaml'
    title: 'EQ'
    type: 'yaml'
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/morphology.yaml'
    title: 'Morphology'
    type: 'yaml'
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/phenotype.yaml'
    title: 'Phenotype'
    type: 'yaml'
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/qualifier.yaml'
    title: 'Qualifier'
    type: 'yaml'
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/ratio.yaml'
    title: 'Ratio'
    type: 'yaml'
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/responsivity.yaml'
    title: 'Responsivity'
    type: 'yaml'
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/responsivityNoEO.yaml'
    title: 'ResponsivityNoEO'
    type: 'yaml'

defaultXSVs:
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/composition/composition.tsv'
    title: 'Composition'
    type: 'tsv'
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/eq/eq.tsv'
    title: 'EQ'
    type: 'tsv'
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/morphology/morphology.tsv'
    title: 'Morphology'
    type: 'tsv'
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/phenotype/phenotype.tsv'
    title: 'Phenotype'
    type: 'tsv'
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/qualifier/qualifier.tsv'
    title: 'Qualifier'
    type: 'tsv'
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/ratio/ratio.tsv'
    title: 'Ratio'
    type: 'tsv'
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/responsivity/responsivity.tsv'
    title: 'Responsivity'
    type: 'tsv'
  - url: 'https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/responsivityNoEO/responsivityNoEO.tsv'
    title: 'ResponsivityNoEO'
    type: 'tsv'
